# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  #watch:
  #  types: started
  schedule:
    - cron: '15 19,20,21,22,23,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    #if: github.event.sender.id == '30381083'
    environment: Production

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Asia/Shanghai
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        curl -O https://raw.githubusercontent.com/w311angg/cp-signin/main/pas.py
    - name: Set proxy
      env:
        config: ${{ secrets.ss_config }}
      run: |
        sudo apt-get install shadowsocks-libev simple-obfs proxychains-ng
        sudo -E sh -c 'echo $config|base64 -d > /etc/shadowsocks-libev/config.json'
        sudo sh -c 'echo "\
        [Unit]
        Description=Shadowsocks
        After=network.target
        [Service]
        ExecStart=ss-local -c /etc/shadowsocks-libev/config.json
        Rnestart=on-abort
        [Install]
        WantedBy=multi-user.target\
        ">/etc/systemd/system/shadowsocks.service'
        sudo systemctl daemon-reload
        sudo systemctl start shadowsocks
        sleep 3s
        systemctl status --no-pager shadowsocks
        sudo sed -i 's/socks4 	127.0.0.1 9050/socks5 127.0.0.1 1080/g' /etc/proxychains4.conf
        sudo sed -i 's/#quiet_mode/quiet_mode/g' /etc/proxychains4.conf
#    - name: Setup tmate session
#      uses: mxschmitt/action-tmate@v3
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ./cookies.txt
          ./num.txt
        key: build-${{ github.run_id }}
        restore-keys: |
          build-
    - name: Run
      env:
        on: ${{ github.event_name }}
        pass: ${{ secrets.mail_password }}
        account: ${{ secrets.account }}
        password: ${{ secrets.password }}
        sender: ${{ secrets.mail_account }}
        to: ${{ secrets.mail_account }}
        host: ${{ secrets.host }}
        pw: ${{ secrets.pw }}
        raccount: ${{ secrets.reward }}
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 5
        command: |
          proxychains python -u checkHash.py
        on_retry_command: sudo systemctl restart shadowsocks
