# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  #watch:
  #  types: started
  schedule:
    - cron: '15 23,5,10,16 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    #if: github.event.sender.id == '30381083'
    environment: Production

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Asia/Shanghai
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Set proxy
      uses: w311ang/setproxy@main
      with:
        config: ${{ secrets.ss_config }}
#    - name: Setup tmate session
#      uses: mxschmitt/action-tmate@v3
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ./cookies.txt
          ./num.txt
          ./isnewday.txt
        key: build-${{ github.run_id }}
        restore-keys: |
          build-
    - name: Run
      env:
        on: ${{ github.event_name }}
        pass: ${{ secrets.mail_password }}
        account: ${{ secrets.account }}
        password: ${{ secrets.password }}
        sender: ${{ secrets.mail_account }}
        to: ${{ secrets.mail_account }}
        host: ${{ secrets.host }}
        pw: ${{ secrets.pw }}
        raccount: ${{ secrets.reward }}
        jmail: ${{ secrets.JMAIL_PASSWORD }}
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 5
        command: |
          proxychains python -u ckhash.py
        on_retry_command: sudo systemctl restart shadowsocks-libev-local@client; sleep 5s
    - uses: gautamkrishnar/keepalive-workflow@master
